---
title: "Before the workshop"
---


For this workshop, we ask that you come prepared with a laptop that has the most recent versions of [R] and [RStudio] installed, and our [workshop materials] downloaded to your Desktop. 

<p>&nbsp;</p>

**We cannot provide service for installation the day of the workshop.**


<p>&nbsp;</p>

Installation
------------

Even if you already have [R] installed on your system, you really should make
sure its up to date. This ensures that there are no problems due to outdated
software. For more details about installing [R], [RStudio], and keeping
everything up to date, UBC's [STAT545] page is an excellent resource.



<p>&nbsp;</p>


Updating programs
------------

If you already have R and RStudio installed in your computer, you can update them using this resource [3 Methods to update R on RStudio].


<p>&nbsp;</p>


Version Verification
------------

Once you have installed [R], we should verify that you have the correct version.

1. RStudio on your computer
2. Enter the following in the R console after the `>`    
        
        R.version.string == "R version 4.2.1 (2022-06-23 ucrt)"
        
3. Make sure the result is **`[1] TRUE`**    
    (If the result is `[1] FALSE`, please quit R and try the installation/updating procedure again)



<p>&nbsp;</p>




[3 Methods to update R on RStudio]: https://www.linkedin.com/pulse/3-methods-update-r-rstudio-windows-mac-woratana-ngarmtrakulchol
[stat545]: http://stat545.com/block000_r-rstudio-install.html
[R]: https://cran.r-project.org/bin/windows/base/
[RStudio]: https://www.rstudio.com/products/rstudio/download/#download
[dplyr]: https://dplyr.tidyverse.org
[ggplot2]: https://ggplot2.tidyverse.org
[plotrix]: https://crantastic.org/packages/plotrix
[RColorBrewer]: https://www.datanovia.com/en/blog/the-a-z-of-rcolorbrewer-palette/
[ggpubr]: https://rpkgs.datanovia.com/ggpubr/
[Slides_IntroR_2020_Webinar_Part1]: https://github.com/everhartlab/APS_IntroR_2020/blob/master/docs/slides/IntroR_2020_Webinar_Part1_2-19-2020.pdf
[Slides_IntroR_2020_Webinar_Part2]: https://github.com/everhartlab/APS_IntroR_2020/blob/master/docs/slides/IntroR_2020_Webinar_Part2_2-26-2020.pdf
